### ISSUE TITLE
Attempting to run demo: SurfaceRendererDemo1 - Fails

### ISSUE THREAD

**Issue by charlesdavid** [jfree/orson-charts#7]
There are unresolved compilation problems in the download (java 1.8 compatability)
Here are the errors:
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The return types are incompatible for the inherited methods ColorScale.getRange(), AbstractColorScale.getRange()
	Type mismatch: cannot convert from org.jfree.data.Range to com.orsoncharts.Range
	The method percent(double) is undefined for the type Range
```
I think this is also causing the constructor to choke in the demo:
`The constructor GradientColorScale(Range, Color, Color) is undefined`

I use JFreeChart quite a bit and would like to now add 3d charts... thus hoping this project is active and well maintained :-) Cheers!

**Comment by charlesdavid** [comment]
/**
     * Returns a font for "Font Awesome" (http://fontawesome.io) at the 
     * specified size.
     * 
     * @param size  the point size.
     * 
     * @return A font. 
     */
    public static Font getFontAwesomeFont(int size) {
        if (FONT_AWESOME == null) {
            try {
                InputStream in = DisplayPanel3D.class.getResourceAsStream(
                        "fontawesome-webfont.ttf");
                FONT_AWESOME = Font.createFont(Font.TRUETYPE_FONT, in);
            } catch (FontFormatException ex) {
                Logger.getLogger(Panel3D.class.getName()).log(Level.SEVERE, 
                        null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Panel3D.class.getName()).log(Level.SEVERE, 
                        null, ex);
            }
        }
        return FONT_AWESOME.deriveFont(Font.PLAIN, size);
    }

**This method is a real problem for java applications not using the internet!**

**Why??? Just load a font FGS!**

**And, of course, it doesn't work... probably the website changed.**

May 12, 2019 4:42:31 PM com.orsoncharts.graphics3d.swing.DisplayPanel3D getFontAwesomeFont
SEVERE: null
java.io.IOException: Problem reading font data.
	at java.awt.Font.createFont0(Unknown Source)
	at java.awt.Font.createFont(Unknown Source)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.getFontAwesomeFont(DisplayPanel3D.java:85)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.createToolBar(DisplayPanel3D.java:168)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.<init>(DisplayPanel3D.java:127)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.<init>(DisplayPanel3D.java:110)
	at support.ScatterPlot3DDemo1.createDemoPanel(ScatterPlot3DDemo1.java:61)
	at support.ScatterPlot3DDemo1.<init>(ScatterPlot3DDemo1.java:42)
	at support.ScatterPlot3DDemo1.main(ScatterPlot3DDemo1.java:124)

Exception in thread "main" java.lang.NullPointerException
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.getFontAwesomeFont(DisplayPanel3D.java:94)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.createToolBar(DisplayPanel3D.java:168)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.<init>(DisplayPanel3D.java:127)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.<init>(DisplayPanel3D.java:110)
	at support.ScatterPlot3DDemo1.createDemoPanel(ScatterPlot3DDemo1.java:61)
	at support.ScatterPlot3DDemo1.<init>(ScatterPlot3DDemo1.java:42)
	at support.ScatterPlot3DDemo1.main(ScatterPlot3DDemo1.java:124)

**Comment by charlesdavid** [comment]
**OK, this code is super buggy...can not even get demos to work...**
**Another nail in coffin to using this is that the code will not run because it can not find the LocalizationBundle...
Sure someone forgot about this... it is in jfree, but not orson....**

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.orsoncharts.graphics3d.swing.ZoomInAction.<init>(ZoomInAction.java:77)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.createToolBar(DisplayPanel3D.java:181)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.<init>(DisplayPanel3D.java:135)
	at com.orsoncharts.graphics3d.swing.DisplayPanel3D.<init>(DisplayPanel3D.java:114)
	at support.Plot_XYZ.createDemoPanel(Plot_XYZ.java:67)
	at support.Plot_XYZ.<init>(Plot_XYZ.java:47)
	at support.Plot_XYZ.main(Plot_XYZ.java:117)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.orsoncharts.Resources, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.orsoncharts.Resources.<clinit>(Resources.java:45)
	... 7 more
Caused by: java.lang.ClassCastException: com.orsoncharts.Resources cannot be cast to ResourceBundle
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2664)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1518)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1482)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1370)
	... 9 more

**After too much time trying to get one chart to work, I am done trying. Glad to give this a fair shake...
WHEN I CAN GET A DEMO THAT RUNS OUT OF THE BOX.**

**Comment by jfree** [comment]
I get that you are frustrated, but there is no need to be a dick about it!

> Type mismatch: cannot convert from org.jfree.data.Range to com.orsoncharts.Range

This first issue is because you are combining code from JFreeChart and code from Orson Charts and those types are not the same.  I can't magically make code that you put together compile, you have to take care of that.

> This method is a real problem for java applications not using the internet!

The font is retrieved from the jar file, NOT the internet, and if you use the prebuilt jar from Maven Central, or build it using the Maven pom.xml you'll find that it works fine.  However, you've compiled the code yourself, I guess using an IDE, and not done it properly.  I can't fix that.

> Another nail in coffin to using this is that the code will not run because it can not find the LocalizationBundle...

Same problem, you've compiled the code yourself (ignoring the provided pom.xml) and not copied over the resources folder.

> WHEN I CAN GET A DEMO THAT RUNS OUT OF THE BOX.

Funnily enough, if you go to the jfree-demos repo:

https://github.com/jfree/jfree-demos

and clone it, then run:

`mvn clean install`

it will create a jar file for you in the `target` directory that you can run like this:

`java -jar jfree-demos-1.2-jar-with-dependencies.jar`
